language: node_js
node_js:
  - 6.11.2

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
before_install:
  - pip install --user codecov

after_sucess:
  - codecov --file coverage/lcov.info --disable search

env:
    - DATABASE_URL=postgres://postgres@localhost/travisdb
